apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort  # Pour accéder depuis ton localhost
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80        # Port du service
      targetPort: 80  # Port du container
      nodePort: 30001 # Port exposé sur ta machine
